// -------COMMON ---------
export const LOG_ERROR = 'LOG_ERROR'
export const UPLOAD_FILE = 'UPLOAD_FILE'
export const CLEAR_FILE = 'CLEAR_FILE'

// ------- USER --------
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT = 'LOGOUT'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const VERIFY_SELF = 'VERIFY_SELF'
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS'
export const VERIFY_FAILED = 'VERIFY_FAILED'

export const REFRESH_SUCCESS = 'REFRESH_SUCCESS'
export const REFRESH_FAILED = 'REFRESH_FAILED'

export const LOAD_SELF = 'LOAD_SELF'
export const LOAD_SELF_CREATED_POST = 'LOAD_SELF_CREATED_POST'
export const LOAD_SELF_MARKED_POST = 'LOAD_SELF_MARKED_POST'

export const UPDATE_SELF = 'UPDATE_SELF'
export const UPDATE_AVATAR = 'UPDATE_AVATAR'
export const UPDATE_SELF_FAILED = 'UPDATE_SELF_FAILED'

export const LOAD_USER = 'LOAD_USER'
export const LOAD_USER_CREATED_POST = 'LOAD_USER_CREATED_POST'
export const LOAD_USER_MARKED_POST = 'LOAD_USER_MARKED_POST'

export const WHITE_LIST_EMAIL = 'WHITE_LIST_EMAIL'
export const CLEAN_WHITE_LIST_EMAIL = 'CLEAN_WHITE_LIST_EMAIL'

export const GET_SELF_EXPERT_APPLICATION = 'GET_SELF_EXPERT_APPLICATION'
export const POST_SELF_EXPERT_APPLICATION = 'POST_SELF_EXPERT_APPLICATION'
export const UPDATE_SELF_EXPERT_APPLICATION = 'UPDATE_SELF_EXPERT_APPLICATION'

// ----- POST -----
export const ADD_POST = 'ADD_POST'
export const GET_POST = 'GET_POST'
export const GET_POST_RATING_DETAIL = 'GET_POST_RATING_DETAIL'
export const LIST_POSTS = 'LIST_POSTS'
export const LIST_PROMO_POSTS = 'LIST_PROMO_POSTS'
export const APPEND_POSTS = 'APPEND_POSTS'
export const MARK_POST = 'MARK_POST'
export const UPDATE_POST = 'UPDATE_POST'

// ----- TEAM -----
export const GET_TEAM = 'GET_TEAM'
export const UPDATE_TEAM = 'UPDATE_TEAM'
export const ADD_TEAM_MEMBER = 'ADD_TEAM_MEMBER'
export const REM_TEAM_MEMBER = 'REM_TEAM_MEMBER'
export const SET_IS_ADVISOR = 'SET_IS_ADVISOR'

// ----- COMMENT -----
export const GET_COMMENTS = 'GET_COMMENTS'

export const POST_COMMENT = 'POST_COMMENT'
export const REPLY_COMMENT = 'REPLY_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

export const APPEND_COMMENT = 'APPEND_COMMENT'
export const APPEND_REPLY = 'APPEND_REPLY'
export const REMOVE_COMMENT_LOCALLY = 'REMOVE_COMMENT_LOCALLY'
