// ------- ACCOUNT --------
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const LOG_IP = 'LOG_IP'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const REFRESH_SUCCESS = 'REFRESH_SUCCESS'

export const LOAD_SELF = 'LOAD_SELF'
export const LOAD_SELF_MARKED_PROJECT = 'LOAD_SELF_MARKED_PROJECT'
export const LOAD_SELF_RATED_PROJECTS = 'LOAD_SELF_RATED_PROJECTS'
export const APPEND_SELF_RATED_PROJECT = 'APPEND_SELF_RATED_PROJECT'

export const UPDATE_SELF = 'UPDATE_SELF'
export const SET_SELF_TYPE = 'SET_SELF_TYPE'

export const LOAD_USER = 'LOAD_USER'
export const LOAD_USER_INFO = 'LOAD_USER_INFO'
export const LOAD_USER_MARKED_PROJECT = 'LOAD_USER_MARKED_PROJECT'
export const LOAD_USER_RATED_PROJECTS = 'LOAD_USER_RATED_PROJECTS'

export const FOLLOW_USER = 'FOLLOW_USER'
export const LOAD_SELF_FOLLOWERS = 'LOAD_SELF_FOLLOWERS'
export const LOAD_SELF_FOLLOWINGS = 'LOAD_SELF_FOLLOWINGS'
export const LOAD_USER_FOLLOWERS = 'LOAD_USER_FOLLOWERS'
export const LOAD_USER_FOLLOWINGS = 'LOAD_USER_FOLLOWINGS'

export const GET_SELF_ANALYST_APPLICATION = 'GET_SELF_ANALYST_APPLICATION'
export const POST_SELF_ANALYST_APPLICATION = 'POST_SELF_ANALYST_APPLICATION'
export const UPDATE_SELF_ANALYST_APPLICATION = 'UPDATE_SELF_ANALYST_APPLICATION'

export const LOAD_ANALYSTS = 'LOAD_ANALYSTS'
// ----- PROJECT -----
export const CREATE_PROJECT = 'CREATE_PROJECT'
export const GET_PROJECT = 'GET_PROJECT'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'

export const SEARCH_PROJECTS = 'SEARCH_PROJECTS'

export const GET_PROJECT_STAT = 'GET_PROJECT_STAT'
export const LIST_PROJECTS = 'LIST_PROJECTS'
export const PROMO_PROJECTS = 'PROMO_PROJECTS'
export const UNRATED_PROJECTS = 'UNRATED_PROJECTS'
export const APPEND_PROJECTS = 'APPEND_PROJECTS'

export const MARK_PROJECT = 'MARK_PROJECT'

export const GET_PROJECT_TAGS = 'GET_PROJECT_TAGS'

export const GET_PROJECT_RATING_DETAIL = 'GET_PROJECT_RATING_DETAIL'
export const CREATE_PROJECT_RATING_DETAIL = 'CREATE_PROJECT_RATING_DETAIL'
export const UPDATE_PROJECT_RATING_DETAIL = 'UPDATE_PROJECT_RATING_DETAIL'

// ----- COMPANY -----
export const GET_COMPANY = 'GET_COMPANY'
export const GET_COMPANY_MEMBERS = 'GET_COMPANY_MEMBERS'
export const APPLY_COMPANY = 'APPLY_COMPANY'
export const SEARCH_COMPANY = 'SEARCH_COMPANY'

export const CREATE_COMPANY = 'CREATE_COMPANY'

export const UPDATE_COMPANY = 'UPDATE_COMPANY'
export const CREATE_COMPANY_MEMBER = 'CREATE_COMPANY_MEMBER'
export const ADD_COMPANY_MEMBER = 'ADD_COMPANY_MEMBER'
export const REMOVE_COMPANY_MEMBER = 'REMOVE_COMPANY_MEMBER'
export const APPROVE_COMPANY_MEMBER = 'APPROVE_COMPANY_MEMBER'
export const REJECT_COMPANY_MEMBER = 'REJECT_COMPANY_MEMBER'
export const ADD_COMPANY_ADMIN = 'ADD_COMPANY_ADMIN'
export const GET_COMPANY_WALLET = 'GET_COMPANY_WALLET'
export const SUBMIT_COMPANY_PROMOTION_APPLICATION = 'SUBMIT_COMPANY_PROMOTION_APPLICATION'
export const GET_COMPANY_PROMOTION_APPLICATION = 'GET_COMPANY_PROMOTION_APPLICATION'

export const GET_COMPANY_ADMINS = 'GET_COMPANY_ADMINS'
export const LEAVE_COMPANY = 'LEAVE_COMPANY'

// ----- TEAM -----
export const GET_TEAM = 'GET_TEAM'
export const UPDATE_TEAM = 'UPDATE_TEAM'
export const ADD_TEAM_MEMBER = 'ADD_TEAM_MEMBER'
export const REM_TEAM_MEMBER = 'REM_TEAM_MEMBER'

// ----- COMMENT -----
export const POST_FEED = 'POST_FEED'
export const POST_USER_FEED = 'POST_USER_FEED'
export const POST_PROJECT_FEED = 'POST_PROJECT_FEED'
export const REPLY_FEED = 'REPLY_FEED'
export const DELETE_FEED = 'DELETE_FEED'
export const APPEND_REPLY = 'APPEND_REPLY'

export const LOAD_MY_FEEDS = 'LOAD_MY_FEEDS'
export const LOAD_PROJECT_FEEDS = 'LOAD_PROJECT_FEEDS'
export const LOAD_USER_FEEDS = 'LOAD_USER_FEEDS'

// ----- Notifications ----
export const LOAD_UNREAD_NOTIFICATIONS = 'LOAD_UNREAD_NOTIFICATIONS'
export const LOAD_READ_NOTIFICATIONS = 'LOAD_READ_NOTIFICATIONS'
export const LOAD_ALL_NOTIFICATIONS = 'LOAD_ALL_NOTIFICATIONS'
export const READ_NOTIFICATION = 'READ_NOTIFICATION'
export const READ_ALL_NOTIFICATION = 'READ_ALL_NOTIFICATION'

// ----- Wallet ----
export const LOAD_WALLET = 'LOAD_WALLET'

// ----- Utils ----
export const SET_IS_ADVISOR = 'SET_IS_ADVISOR'
export const WHITE_LIST_EMAIL = 'WHITE_LIST_EMAIL'
export const CLEAN_WHITE_LIST_EMAIL = 'CLEAN_WHITE_LIST_EMAIL'
export const SET_RESEND_EMAIL_TIME_LIMIT = 'SET_RESEND_EMAIL_TIME_LIMIT'
export const FOLLOW_UP_STEP = 'FOLLOW_UP_STEP'
export const NEW_COMPANY_NAME = 'NEW_COMPANY_NAME'
